spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  output:
    ansi:
      enabled: ALWAYS

  mvc:
    uri-encoding: UTF-8

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update # or your preferred strategy
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
